config/routes.rb
WeLike::Application.routes.draw do
  
  
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :wishes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root 'static_pages#home'
  
  
  match '/users', to: 'users#index', via: :get  
  
  match '/help', to: 'static_pages#help', via: :get
  match '/about', to:  'static_pages#about', via: :get
  match '/contact', to: 'static_pages#contact', via: :get

  

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  mount_uploader :avatar, AvatarUploader       
         
  has_many :wishes, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name: "Relationship",
                                   dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  
  def feed
    Wish.from_users_followed_by(self)
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
  
end

app/models/wish.rb
class Wish < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  
  belongs_to :user
  
  validates :title, presence: true
  validates :picture, presence: true
  validates :price, presence: true
  validates :content, length: {maximum: 300 }
  validates :user_id, presence: true
  
  default_scope order: 'wishes.created_at DESC'
  
  def self.from_users_followed_by(user)
      followed_user_ids = "SELECT followed_id FROM relationships
                           WHERE follower_id = :user_id"
      where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_in_path_for(resource)
      current_user
  end
  
  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
  
  
  
  
  protected
 
      def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
        devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password, :remember_me) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
      end
      
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
  
  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if user_signed_in?
      @wish = current_user.wishes.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @wishes = Wish.last(6)
    end
  end
 
  
  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @wishes = @user.wishes.paginate(page: params[:page])
  end
  
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
 # def avatar_url(user)
  #  if user.avatar?
  #    user.avatar
  #  else
  #    default_url="#{root_url}images/guest.png"
  # end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar, :avatar_remote_url)
  end
  
  def wish_params
    params.require(:wish).permit(:content, :avatar, :title, :price, :picture)
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user, only: :destroy
  
  def create
    @wish = current_user.wishes.build(wish_params)
    if @wish.save
      flash[:success] = "Wish  created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def destroy
    @wish.destroy
    redirect_to current_user
  end
  
  def index
  end
  
  private
  
  def correct_user
    @wish = current_user.wishes.find_by_id(params[:id])
    redirect_to root_path if @wish.nil?
  end
  
  def wish_params
    params.require(:wish).permit(:content, :picture, :remote_picture_url, :title, :price, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "We-like"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def current_user?(user)
    user == current_user
  end
  
  def avatar_for(user)
    image_tag(avatar_url, alt: user.username, class: "avatar")
  end
end

app/helpers/wishes_helper.rb
module WishesHelper
  
  def wrap(content)
    sanitize(raw(content.split.map { |s| wrap_long_string(s) }.join(' ')))
  end
  
  private
  
    def wrap_long_string(text, max_width = 30)
          zero_width_space = "&#8203;"
          regex = /.{1,#{max_width}}/
          (text.length < max_width) ? text :
                                      text.scan(regex).join(zero_widh_space)
    end 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    We-like
  </small>
  <nav>
		<ul>
			<li><%= link_to "О Сервисе", about_path %></li>
			<li><%= link_to "Контакты", contact_path %></li>
		</ul> 
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "We-like", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Главная", root_path %></li>
					<li><%= link_to "Помощь", help_path %></li>
					<% if user_signed_in? %>
					<li><%= link_to "Пользователи", users_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_registration_path %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
							</li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to "Войти", new_user_session_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer'%>
	</div>
</body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="wishes">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	
	<span class="user">
		<%= link_to feed_item.user.username, feed_item.user %>
	</span>
	<div class="row">
		<div class="span2">
			<b><%= feed_item.title %></b>
			<%= image_tag(feed_item.picture_url(:thumb), class: "img-polaroid") %>
			<%= feed_item.price %>
		</div>
		<div class="span6">
			<div class="content">
				<%= feed_item.content %>
			</div>
		</div>
	<span id="timestamp" class="pull-right">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
</div>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		подписки
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		подписчики
	</a>
</div>

app/views/shared/_unreghome.html.erb
<div class="jumbotron">
  <h3>Дайте миру узнать, что вам нравится и чего вы заслуживаете!</h3>
	<p class="lead">
	Создайте свой список желаний и делитесь им со своими друзьями.
	</p>
	<%= link_to "Зарегистрироваться!", new_user_registration_path, class: "btn btn-large btn-success" %>
</div>
<hr>
<div class="row-fluid marketing">
	<div class="span6">
		<h3>Записывайте</h3>
		<p><%= image_tag('1.png', class: "icon") %>
			Нашли прикольную вещицу? Думаете о покупуке чего-нибудь новенького? Наш сервис поможет собрать все, что в одном месте и ничего не забыть.
		</p>
	</div>
	<div class="span6">
		<h3>Делитесь</h3>
		<p><%= image_tag('2.png', class: "icon") %>
		Сервис We-like позволяет легко поделиться тем, что Вам нравится со всеми кого вы знаете. Вы больше не будете получать подарки, которые вы не 		 хотели.
	</p>
	</div>
</div>
<hr>
<div class="pull-left">
	<b>Последние добавленные:</b>
</div>
<div class="pull-right">Всего желаний
<span class="badge badge-inverse">
<%= Wish.count %>
</span>
</div>
<br>
<%= render 'shared/wishes'%>

app/views/shared/_user_info.html.erb
<a href="<%= current_user %>"></a>
<h1>
	<%= image_tag(current_user.avatar.thumb, alt: current_user.username, class: "avatar") %>
	<%= current_user.username %>
</h1>
<span>
	<%= link_to "просмотр профиля", current_user %>
</span>
<span>
	<%= current_user.wishes.count %> Желания
</span>

app/views/shared/_wish_form.html.erb
<%= form_for @wish, :html => { :multipart => true } do |f| %>
<div class="field">
	<%= f.text_field :title, placeholder: "Назовите желание" %>
	<%= f.file_field :picture %>
	<%= f.text_field :remote_picture_url, placeholder: "Ссылка на картинку" %>
	<%= f.text_area :content, placeholder: "Описание желания" %>
	<%= f.text_field :price, placeholder: "Цена" %>
</div>
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_wishes.html.erb
<div class="row-fluid">
<% @wishes.reverse_each do |wish| %>
<ul class="thumbnails">
	<li class="span3 offset1">
		<div><%= image_tag(wish.picture_url(:thumb), class: "img-polaroid") if wish.picture? %></div>
			<%= wish.title %>
			
</li>

<% end %>
</ul>

app/views/static_pages/about.html.erb
<h1>О Сервисе</h1>
<p>Данный сервис был создан с целью предоставления пользователям возможности записывать и сохранять те вещи, которые они хотят.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Контакты') %>
<h1>Обратная связь</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Помощь')%>
<h1>Помощь</h1>
<hr>
<h2>Как завести свой список желаний?</h2>
<p>
	Для того, чтобы начать составлять свой список, сначала Вам нужно зарегистрироваться. Для этого необхомо в соответствущей форме указать Ваш адрес электронной почты и придумать пароль.
</p>
<h2>Что можно указывать в своем желании?</h2>
<p>
Как минимум, написать само желание – название и краткое описание того, что вы хотите получить. Если это книга, напишите ее название, автора и не забудьте упомянуть, что это именно книга (например так: книга "Приключения Алисы в стране чудес", Л. Кэррол). Если это мобильный телефон, можно написать так: "Мобильный телефон Nokia 6125", или так: "Мобильный телефон" и комментарий: хочу с фотокамерой, mp3-плейером и обязательно раскладушку.


Если вы написали список подарков, которые хотели бы получить на день рождения, Новый Год или Первое сентября, не забудьте указать повод.

Также можно дать ссылку на описание товара на сайте производителя или на страницу в интернет-магазине, указать ориентировочную цену и добавить фотографию.
</p>
<h2>Как добавить картинку к желанию?</h2>
<p>Есть два способа:<br>
1. Загрузить картинку с вашего компьютера, нажав кнопку "Browse".</br>
2. Eсли картинка находится на каком-либо сайте в интернете, впишите в поле адреса картинки ее полный веб-адрес (URL). Для этого нужно кликнуть правой кнопкой мыши по картинке на сайте и выбрать в выпадающем меню пункт "Скопировать адрес изображения" или "Copy Image Location". Затем зайти в форму добавления желания и вставить из буфера сохраненный адрес в поле для адреса картинки (правая кнопка мыши и пункт "Вставить" или клавиатурная комбинация Ctrl+V).
</p>

<h2>Что делать, если вы забыли пароль?</h2>
<p>
Если вы указали в настройках e-mail для восстановления пароля, вам нужно зайти по ссылке "Забыли пароль?" с первой страницы и ввести свой логин. Вы получите письмо с ссылкой, зайдя по которой вы сможете указать новый пароль.
</p>

<h2>Списки друзей (френдленты)</h2>
<p>
	Чтобы видеть все обновления в вишлистах ваших друзей на одной странице, создайте свою френдленту. Зайдите на страницу вашего друга и кликните по ссылке "Добавить в друзья", находящейся под его именем. Список можно редактировать в разделе Настройки / Список друзей.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if user_signed_in? %>	
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats'%>
		</section>
		<section>
			<%= render 'shared/wish_form' %>
		</section>
	</aside>
	<div class="span8">
		<h3>Лента желаний</h3>
		<%= render 'shared/feed' %>
	</div>
	<% else %>
	<%= render 'shared/unreghome'%>

<% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
<div><%= f.hidden_field :followed_id %></div>
<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
	<% if current_user.following?(@user) %>
	<%= render 'unfollow'%>
	<% else %>
	<%= render 'follow' %>
	<% end %>
</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user), html: 	{method: :delete}, remote: true) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= image_tag(user.avatar_url(:thumb)) %>
	<%= link_to user.username, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.username)%>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= image_tag(@user.avatar_url(:thumb), alt: @user.username, class: "avatar") %>
			<%= @user.username %></h1>
		</section>
		<section>
			<%= render 'shared/stats'%>
		</section>
	</aside>
	<div class="span8">
		<%= render 'follow_form' if user_signed_in? %>
		<% if @user.wishes.any? %>
			<h3>Желаний (<%= @user.wishes.count %>)</h3>
			<ol class="wishes">
				<%= render @wishes%>
			</ol>
			<%= will_paginate @wishes %>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class=row>
	<aside class=span4>
		<section>
			<h1><%= @user.username %></h1>
			<span><%= link_to  "view my profile", @user %></span>
			<span><b>Wishes:</b><%= @user.wishes.count %></span>
		</section>
		<section>
			<%= render 'shared/stats' %>
			<% if @users.any? %>
			<div class="user_avatars">
				<% @users.each do |user| %>
				<%= link_to user.username %>
				<% end %>
			</div>
			<% end %>
		</section>
	</aside>
	<div class="span8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
		<ul class="users">
			<%= render @users%>
		</ul>
		<%= will_paginate %>
		<% end %>
	</div>
</div>

app/views/wishes/_wish.html.erb
<li>
	<div class="row">
		<div class="span2">
		<div><b><%= wish.title %></b></div>
		<%= image_tag(wish.picture_url(:thumb), class: "img-polaroid") %>
		<div><%= wish.price %></div>
	</div>
<div class="span6">
			<div class="content"><%= wish.content %></div>
			<% if current_user?(wish.user) %>
			<div class="pull-right">
			<%= link_to 'delete', wish, class: "badge badge-important", method: :delete,
																	data: { confirm: "You sure?" },
																	title: "delete" %>
																</div>
		  <% end %>
			<span id="timestamp" class="pull-right">
		Posted <%= time_ago_in_words(wish.created_at) %> ago.
	</span>
	</div>
	</div>
	
</li>